test husky

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,12 +1,22 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-# Get the list of staged files
-staged_files=$(git diff --cached --name-only -- 'src/*.tsx' 'src/*.ts')
 
-git stash
+# Stash unstaged changes
+git stash --keep-index
 
 # Run ESLint on staged files
-npx eslint $staged_files --fix
+npx eslint --fix --quiet -- "$(git diff --cached --name-only)"
 
-git stash pop
+# Check ESLint exit status
+eslint_exit_status=$?
+
+# Pop stashed changes only if ESLint ran successfully
+if [ $eslint_exit_status -eq 0 ]; then
+  git stash pop
+else
+  echo "ESLint found errors. Stashed changes were not popped."
+fi
+
+# Exit with the ESLint exit status
+exit $eslint_exit_status
